version: '3.8'

services:
  
  # PostgreSQL Database Service
  kong-database:
    image: postgres:latest
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    networks:
      - kong-net

  # Kong Migrations Service (runs only once to bootstrap the database)
  kong-migrations:
    image: kong:latest
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    networks:
      - kong-net
    command: kong migrations bootstrap
    restart: 'on-failure'

  # Kong Gateway Service
  kong:
    image: kong:latest
    depends_on:
      - kong-migrations
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"    # Proxy access port
      - "8001:8001"    # Admin API port
      - "8443:8443"    # SSL Proxy access
      - "8444:8444"    # SSL Admin API
    networks:
      - kong-net
    restart: always

networks:
  kong-net:
    driver: bridge
