# Use an official Python runtime as a parent image
FROM python:3.10  
# Match Python version specified in pyproject.toml

LABEL maintainer="shafiq00786@hotmail.com"

# Set the working directory in the container
WORKDIR /code

# Install system dependencies required for confluent-kafka and other Python packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    libsasl2-dev \
    librdkafka-dev \  
    # Required for confluent-kafka
    protobuf-compiler  
# For Protobuf

# Install Poetry
RUN pip install poetry

# Copy the current directory contents into the container at /code
COPY . /code/

# Configuration to avoid creating virtual environments inside the Docker container
RUN poetry config virtualenvs.create false

# Install Python dependencies
RUN poetry install --no-root

# Make port 8003 available to the world outside this container
EXPOSE 8003

# Run the app. CMD can be overridden when starting the container
CMD ["poetry", "run", "uvicorn", "services.users.users.producer.main:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]
